[package]
name = "mq-h3"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
h3wire = "0.1"
mq-transport-api = { path = "../mq-transport-api" }
log = { workspace = true }

[features]
test-support = []

[dev-dependencies]
mq-runtime = { path = "../mq-runtime", features = ["test-support"] }
proptest = { workspace = true }
