[package]
name = "mq-proxy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
mq-runtime = { path = "../mq-runtime" }
mq-transport-api = { path = "../mq-transport-api" }
mq-wire = { path = "../mq-wire" }
log = { workspace = true }
subtle = { workspace = true }

[dev-dependencies]
mq-runtime = { path = "../mq-runtime", features = ["test-support"] }
mq-proxy = { path = ".", features = ["test-support"] }

[features]
test-support = []
