# /var/log/mqproxy is created by the units' LogsDirectory=, so only the config
# dir is declared here.
# Type Path         Mode UID     GID     Age Argument
d     /etc/mqproxy  0750 mqproxy mqproxy -
