[package]
name = "mqproxy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
mq-proxy = { path = "../mq-proxy" }
mq-runtime = { path = "../mq-runtime" }
mq-transport = { path = "../mq-transport" }
mq-transport-api = { path = "../mq-transport-api" }
mq-h3 = { path = "../mq-h3" }
mq-linux = { path = "../mq-linux" }
clap = { workspace = true }
log = { workspace = true }

[dev-dependencies]
mq-wire = { path = "../mq-wire" }
signal-hook = { workspace = true }
mio = { workspace = true }
